version: '3.1'

services:
  agit-db:
    container_name: agit-mysql
    image: mysql:8.0.22
    platform: linux/amd64
    volumes:
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./init/:/docker-entrypoint-initdb.d/
      - ./agit_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: agit
    ports:
      - 3306:3306